hl.on("hyprland.start", function()
  hl.exec_cmd("qs -c noctalia-shell")
  hl.exec_cmd("keymapp", { workspace = "1 silent" })
  hl.exec_cmd("/usr/bin/syncthing serve", { workspace = "2 silent" })
  hl.exec_cmd("Telegram", { workspace = "9 silent" })
  hl.exec_cmd("swaync")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("wl-paste -t text --watch clipman store --no-persist")
  hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 28")
  -- hl.exec_cmd("awww-daemon")
  -- hl.exec_cmd("~/bin/backgrounds.sh ~/Pictures/00-wallpapers/forest 300")
end)
